[package]
name = "timeman"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tm"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
